[workspace.package]
license = "MIT-0"
authors = ["Parity Technologies <admin@parity.io>", "Xode DAO <admin@xode.net>"]
homepage = "https://xode.net"
repository = "https://github.com/xode-blockchain/xode-blockchain"
version = "0.1.0"
edition = "2021"

[workspace.metadata.psvm]
version = "polkadot-stable2506-1"

[workspace]
members = ["node", "pallets/staking", "runtime"]
resolver = "2"

[workspace.dependencies]
# Local Project Pallets
xode-runtime            = { path = "./runtime", default-features = false }
pallet-xode-staking     = { path = "./pallets/staking", default-features = false }

# General Dependencies
async-trait = { version = "0.1.74" }
clap            = { version = "4.5.1", default-features = false }
color-print     = { version = "0.3.5" }
color-eyre      = { version = "0.6.3", default-features = false }
futures         = { version = "0.3.28", default-features = false }
hex-literal     = { version = "0.4.1", default-features = false }
hex             = { version = "0.4.3", default-features = false, features = ["alloc"] }
jsonrpsee       = { version = "0.24.8", default-features = false }
log             = { version = "0.4.17", default-features = false }
primitive-types = { version = "0.12.1", default-features = false, features = ["codec", "num-traits", "scale-info"] }
serde           = { version = "1.0.197", default-features = false, features = ["derive"] }
serde_json      = { version = "1.0.113", default-features = false }
smallvec        = { version = "1.11.1", default-features = false }

# Parity codec
parity-scale-codec  = { version = "3.6.12", default-features = false, features = ["derive"] }
scale-info          = { version = "2.11.1", default-features = false, features = ["derive"] }

# Substrate
assets-common                               = { version = "0.22.0", default-features = false }
frame-benchmarking                          = { version = "41.0.1", default-features = false }
frame-benchmarking-cli                      = { version = "49.1.0" }
frame-executive                             = { version = "41.0.0", default-features = false }
frame-metadata-hash-extension               = { version = "0.9.0", default-features = false }
frame-support                               = { version = "41.0.0", default-features = false }
frame-system                                = { version = "41.0.0", default-features = false }
frame-system-benchmarking                   = { version = "41.0.0", default-features = false }
frame-system-rpc-runtime-api                = { version = "37.0.0", default-features = false }
frame-try-runtime                           = { version = "0.47.0", default-features = false }
pallet-assets                               = { version = "43.0.0", default-features = false }
pallet-asset-conversion                     = { version = "23.0.0", default-features = false }
# pallet-asset-conversion-ops                 = { version = "0.13.0", default-features = false }
pallet-asset-conversion-tx-payment          = { version = "23.0.0", default-features = false }
# pallet-asset-rate                           = { version = "24.0.0", default-features = false }
# pallet-assets-freezer                       = { version = "0.10.0", default-features = false }
pallet-assets-precompiles                   = { version = "0.3.0", default-features = false }
pallet-aura                                 = { version = "40.0.0", default-features = false }
pallet-authorship                           = { version = "41.0.0", default-features = false }
pallet-balances                             = { version = "42.0.0", default-features = false }
pallet-collective                           = { version = "41.0.0", default-features = false }
pallet-contracts                            = { version = "41.0.0", default-features = false }
# pallet-indices                              = { version = "41.0.0", default-features = false }
pallet-message-queue                        = { version = "44.0.0", default-features = false }
pallet-membership                           = { version = "41.0.0", default-features = false }
pallet-preimage                             = { version = "41.0.0", default-features = false }
pallet-revive                               = { version = "0.11.0", default-features = false }
# pallet-root-testing                         = { version = "21.0.0", default-features = false }
pallet-session                              = { version = "41.0.0", default-features = false }
pallet-sudo                                 = { version = "41.0.0", default-features = false }
pallet-timestamp                            = { version = "40.0.0", default-features = false }
pallet-transaction-payment                  = { version = "41.0.0", default-features = false }
pallet-transaction-payment-rpc              = { version = "44.0.0" }
pallet-transaction-payment-rpc-runtime-api  = { version = "41.0.0", default-features = false }
pallet-treasury                             = { version = "40.0.0", default-features = false }
pallet-utility                              = { version = "41.0.0", default-features = false }
pallet-whitelist                            = { version = "40.0.0", default-features = false }
pallet-xcm-precompiles                      = { version = "0.2.0", default-features = false }
sc-basic-authorship                         = { version = "0.50.0", default-features = false }
sc-chain-spec                               = { version = "44.0.0", default-features = false }
sc-cli                                      = { version = "0.53.1", default-features = false }
sc-client-api                               = { version = "40.0.0", default-features = false }
sc-consensus                                = { version = "0.50.0", default-features = false }
sc-executor                                 = { version = "0.43.0", default-features = false }
sc-network                                  = { version = "0.51.1", default-features = false }
sc-network-sync                             = { version = "0.50.0", default-features = false }
sc-offchain                                 = { version = "46.0.0", default-features = false }
sc-rpc                                      = { version = "46.0.0", default-features = false }
sc-service                                  = { version = "0.52.0", default-features = false }
sc-sysinfo                                  = { version = "43.0.0", default-features = false }
sc-telemetry                                = { version = "29.0.0", default-features = false }
sc-tracing                                  = { version = "40.0.0", default-features = false }
sc-transaction-pool                         = { version = "40.1.0", default-features = false }
sc-transaction-pool-api                     = { version = "40.0.0", default-features = false }
sp-api                                      = { version = "37.0.0", default-features = false }
sp-block-builder                            = { version = "37.0.0", default-features = false }
sp-blockchain                               = { version = "40.0.0", default-features = false }
sp-consensus-aura                           = { version = "0.43.0", default-features = false }
sp-core                                     = { version = "37.0.0", default-features = false }
sp-genesis-builder                          = { version = "0.18.0", default-features = false }
sp-inherents                                = { version = "37.0.0", default-features = false }
sp-keyring                                  = { version = "42.0.0", default-features = false }
sp-keystore                                 = { version = "0.43.0", default-features = false }
sp-offchain                                 = { version = "37.0.0", default-features = false }
sp-io                                       = { version = "41.0.1", default-features = false }
sp-runtime                                  = { version = "42.0.0", default-features = false }
sp-session                                  = { version = "39.0.0", default-features = false }
sp-staking                                  = { version = "39.0.0", default-features = false }
sp-std                                      = { version = "14.0.0", default-features = false }
sp-storage                                 	= { version = "22.0.0", default-features = false }
sp-timestamp                                = { version = "37.0.0", default-features = false }
sp-transaction-pool                         = { version = "37.0.0", default-features = false }
sp-version                                  = { version = "40.0.0", default-features = false }
substrate-build-script-utils                = { version = "11.0.0", default-features = false }
substrate-frame-rpc-system                  = { version = "45.0.0", default-features = false }
substrate-prometheus-endpoint               = { version = "0.17.6", default-features = false }
substrate-wasm-builder                      = { version = "27.0.0", default-features = false }
substrate-state-trie-migration-rpc         	= { version = "44.0.0" }
pallet-identity                            	= { version = "41.0.0", default-features = false }

# Polkadot & XCM
pallet-xcm                      = { version = "20.1.2", default-features = false }
polkadot-cli                    = { version = "25.0.0", default-features = false }
polkadot-omni-node-lib        	= { version = "0.7.0" }
polkadot-parachain-primitives   = { version = "17.0.0", default-features = false }
polkadot-primitives             = { version = "19.0.0", default-features = false }
polkadot-runtime-common         = { version = "20.0.0", default-features = false }
xcm                             = { package = "staging-xcm", version = "17.0.0", default-features = false }
xcm-builder                     = { package = "staging-xcm-builder", version = "21.1.0", default-features = false }
xcm-executor                    = { package = "staging-xcm-executor", version = "20.0.1", default-features = false }
xcm-runtime-apis                = { version = "0.8.0", default-features = false }

# Cumulus
cumulus-client-cli                          = { version = "0.24.0", default-features = false }
cumulus-client-collator                     = { version = "0.24.0", default-features = false }
cumulus-client-consensus-aura               = { version = "0.24.0", default-features = false }
cumulus-client-consensus-common             = { version = "0.24.0", default-features = false }
cumulus-client-consensus-proposer           = { version = "0.20.0", default-features = false }
cumulus-client-consensus-relay-chain    		= { version = "0.24.0" }
cumulus-client-network                  		= { version = "0.24.0", default-features = false }
cumulus-client-parachain-inherent     			= { version = "0.18.0" }
cumulus-client-service                      = { version = "0.25.0", default-features = false }
cumulus-pallet-aura-ext                     = { version = "0.21.0", default-features = false }
cumulus-pallet-parachain-system             = { version = "0.21.0", default-features = false }
cumulus-pallet-session-benchmarking         = { version = "22.0.0", default-features = false }
cumulus-pallet-xcm                          = { version = "0.20.0", default-features = false }
cumulus-pallet-xcmp-queue                   = { version = "0.21.0", default-features = false }
cumulus-pallet-weight-reclaim               = { version = "0.7.0", default-features = false }
cumulus-primitives-aura                     = { version = "0.18.0", default-features = false }
cumulus-primitives-core                     = { version = "0.19.0", default-features = false }
cumulus-primitives-parachain-inherent       = { version = "0.19.0", default-features = false }
cumulus-primitives-storage-weight-reclaim   = { version = "8.0.0", default-features = false }
cumulus-primitives-utility                  = { version = "0.21.0", default-features = false }
cumulus-relay-chain-interface               = { version = "0.24.0", default-features = false }
pallet-collator-selection                   = { version = "22.0.0", default-features = false }
parachains-common                           = { version = "22.0.0", default-features = false }
parachain-info                              = { package = "staging-parachain-info", version = "0.21.0", default-features = false }

# ORML
orml-traits         = { version = "1.5.0", default-features = false }
orml-xcm            = { version = "1.5.0", default-features = false }
orml-xcm-support    = { version = "1.5.0", default-features = false }
orml-xtokens        = { version = "1.5.0", default-features = false }

# integritee pallets
pallet-asset-registry   = { default-features = false, git = "https://github.com/integritee-network/pallets.git", branch = "cl/polkadot-stable2506-1" }
xcm-primitives          = { default-features = false, git = "https://github.com/integritee-network/pallets.git", branch = "cl/polkadot-stable2506-1" }

# prometheus-endpoint                         = { version = "0.17.0", default-features = false, package = "substrate-prometheus-endpoint" }

[profile.production]
codegen-units = 1
inherits = "release"
lto = true

[profile.release]
opt-level = 3
panic = "unwind"

[patch.crates-io]
core2 = { git = "https://github.com/bbqsrc/core2", rev = "545e84bcb0f235b12e21351e0c69767958efe2a7" }